/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification_nutrition (void);
GtkWidget* create_Menu_student_nutrition (void);
GtkWidget* create_Menu_admin_nutrition (void);
GtkWidget* create_window1_nutrition (void);
