/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_authentification_nutrition (void)
{
  GtkWidget *authentification_nutrition;
  GtkWidget *fixed1;
  GtkWidget *entry_login_nutrition;
  GtkWidget *entry_pw_nutrition;
  GtkWidget *label_login_nutrition;
  GtkWidget *label_passw_nutrition;
  GtkWidget *checkbutton1_nutrition;
  GtkWidget *student_nutrition;
  GSList *student_nutrition_group = NULL;
  GtkWidget *button_Login_nutrition;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *admin_nutrition;

  authentification_nutrition = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (authentification_nutrition), _("authentification"));
  gtk_window_set_position (GTK_WINDOW (authentification_nutrition), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_default_size (GTK_WINDOW (authentification_nutrition), 500, 500);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (authentification_nutrition), fixed1);

  entry_login_nutrition = gtk_entry_new ();
  gtk_widget_show (entry_login_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_login_nutrition, 160, 112);
  gtk_widget_set_size_request (entry_login_nutrition, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_login_nutrition), 8226);

  entry_pw_nutrition = gtk_entry_new ();
  gtk_widget_show (entry_pw_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_pw_nutrition, 160, 160);
  gtk_widget_set_size_request (entry_pw_nutrition, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_pw_nutrition), 8226);

  label_login_nutrition = gtk_label_new (_("Login :"));
  gtk_widget_show (label_login_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed1), label_login_nutrition, 32, 112);
  gtk_widget_set_size_request (label_login_nutrition, 56, 24);

  label_passw_nutrition = gtk_label_new (_("Password :"));
  gtk_widget_show (label_passw_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed1), label_passw_nutrition, 16, 168);
  gtk_widget_set_size_request (label_passw_nutrition, 96, 16);

  checkbutton1_nutrition = gtk_check_button_new_with_mnemonic (_("Je n'ai pas  un compte"));
  gtk_widget_show (checkbutton1_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1_nutrition, 168, 264);
  gtk_widget_set_size_request (checkbutton1_nutrition, 200, 24);

  student_nutrition = gtk_radio_button_new_with_mnemonic (NULL, _("Student"));
  gtk_widget_show (student_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed1), student_nutrition, 128, 200);
  gtk_widget_set_size_request (student_nutrition, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (student_nutrition), student_nutrition_group);
  student_nutrition_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (student_nutrition));

  button_Login_nutrition = gtk_button_new ();
  gtk_widget_show (button_Login_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed1), button_Login_nutrition, 184, 304);
  gtk_widget_set_size_request (button_Login_nutrition, 128, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_Login_nutrition), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Login"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  admin_nutrition = gtk_radio_button_new_with_mnemonic (NULL, _("Adminstrateur"));
  gtk_widget_show (admin_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed1), admin_nutrition, 256, 200);
  gtk_widget_set_size_request (admin_nutrition, 144, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (admin_nutrition), student_nutrition_group);
  student_nutrition_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (admin_nutrition));

  g_signal_connect ((gpointer) checkbutton1_nutrition, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) student_nutrition, "toggled",
                    G_CALLBACK (on_student_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_Login_nutrition, "clicked",
                    G_CALLBACK (on_button_Login_clicked),
                    NULL);
  g_signal_connect ((gpointer) admin_nutrition, "toggled",
                    G_CALLBACK (on_admin_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification_nutrition, authentification_nutrition, "authentification_nutrition");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, entry_login_nutrition, "entry_login_nutrition");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, entry_pw_nutrition, "entry_pw_nutrition");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, label_login_nutrition, "label_login_nutrition");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, label_passw_nutrition, "label_passw_nutrition");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, checkbutton1_nutrition, "checkbutton1_nutrition");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, student_nutrition, "student_nutrition");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, button_Login_nutrition, "button_Login_nutrition");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, image2, "image2");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, label3, "label3");
  GLADE_HOOKUP_OBJECT (authentification_nutrition, admin_nutrition, "admin_nutrition");

  return authentification_nutrition;
}

GtkWidget*
create_Menu_student_nutrition (void)
{
  GtkWidget *Menu_student_nutrition;
  GtkWidget *fixed2;
  GtkObject *spinbutton_jour_nutrition_adj;
  GtkWidget *spinbutton_jour_nutrition;
  GtkObject *spinbutton_mois_nutrition_adj;
  GtkWidget *spinbutton_mois_nutrition;
  GtkObject *spinbutton_annnee_nutrition_adj;
  GtkWidget *spinbutton_annnee_nutrition;
  GtkWidget *treeview1_nutrition;
  GtkWidget *fixed10;
  GtkWidget *image26;
  GtkWidget *btn_exit_std_nutrition;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image28;
  GtkWidget *label52;
  GtkWidget *label42_nutrition;
  GtkWidget *date_nutrition;
  GtkWidget *jour_nutrition;
  GtkWidget *mois_nutrition;
  GtkWidget *button_rech_std_nutrition;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image4;
  GtkWidget *label8;
  GtkWidget *label_annee_nutrition;
  GtkWidget *image27;

  Menu_student_nutrition = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Menu_student_nutrition, 500, 600);
  gtk_window_set_title (GTK_WINDOW (Menu_student_nutrition), _("Menu student"));
  gtk_window_set_position (GTK_WINDOW (Menu_student_nutrition), GTK_WIN_POS_CENTER);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Menu_student_nutrition), fixed2);

  spinbutton_jour_nutrition_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jour_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jour_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton_jour_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_jour_nutrition, 96, 336);
  gtk_widget_set_size_request (spinbutton_jour_nutrition, 40, 24);

  spinbutton_mois_nutrition_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mois_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mois_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton_mois_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_mois_nutrition, 96, 368);
  gtk_widget_set_size_request (spinbutton_mois_nutrition, 40, 24);

  spinbutton_annnee_nutrition_adj = gtk_adjustment_new (1, 2000, 2021, 1, 10, 10);
  spinbutton_annnee_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_annnee_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton_annnee_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton_annnee_nutrition, 96, 408);
  gtk_widget_set_size_request (spinbutton_annnee_nutrition, 72, 24);

  treeview1_nutrition = gtk_tree_view_new ();
  gtk_widget_show (treeview1_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1_nutrition, 32, 456);
  gtk_widget_set_size_request (treeview1_nutrition, 592, 160);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed10, 0, 0);
  gtk_widget_set_size_request (fixed10, 656, 192);

  image26 = create_pixmap (Menu_student_nutrition, "index6.jpeg");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed10), image26, 8, 8);
  gtk_widget_set_size_request (image26, 296, 176);

  btn_exit_std_nutrition = gtk_button_new ();
  gtk_widget_show (btn_exit_std_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed10), btn_exit_std_nutrition, 584, 8);
  gtk_widget_set_size_request (btn_exit_std_nutrition, 66, 29);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (btn_exit_std_nutrition), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image28 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox17), image28, FALSE, FALSE, 0);

  label52 = gtk_label_new_with_mnemonic (_("Exit"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox17), label52, FALSE, FALSE, 0);

  label42_nutrition = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">Bienvenue dans l'espace \303\251tudiant</span></b>"));
  gtk_widget_show (label42_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), label42_nutrition, 192, 112);
  gtk_widget_set_size_request (label42_nutrition, 328, 64);
  gtk_label_set_use_markup (GTK_LABEL (label42_nutrition), TRUE);

  date_nutrition = gtk_label_new (_("Veuillez saisir la date : "));
  gtk_widget_show (date_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), date_nutrition, 0, 280);
  gtk_widget_set_size_request (date_nutrition, 168, 24);

  jour_nutrition = gtk_label_new (_("Jour :"));
  gtk_widget_show (jour_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), jour_nutrition, 32, 336);
  gtk_widget_set_size_request (jour_nutrition, 48, 16);

  mois_nutrition = gtk_label_new (_("Mois :"));
  gtk_widget_show (mois_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), mois_nutrition, 32, 376);
  gtk_widget_set_size_request (mois_nutrition, 41, 17);

  button_rech_std_nutrition = gtk_button_new ();
  gtk_widget_show (button_rech_std_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), button_rech_std_nutrition, 232, 360);
  gtk_widget_set_size_request (button_rech_std_nutrition, 144, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_rech_std_nutrition), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image4 = create_pixmap (Menu_student_nutrition, "icons8-strawberry-30.png");
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox2), image4, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Recherche "));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox2), label8, FALSE, FALSE, 0);

  label_annee_nutrition = gtk_label_new (_("Ann\303\251e : "));
  gtk_widget_show (label_annee_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed2), label_annee_nutrition, 24, 408);
  gtk_widget_set_size_request (label_annee_nutrition, 72, 24);

  image27 = create_pixmap (Menu_student_nutrition, "icons8-kawaii-bread-40(1).png");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed2), image27, 584, 264);
  gtk_widget_set_size_request (image27, 77, 64);

  g_signal_connect ((gpointer) treeview1_nutrition, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) btn_exit_std_nutrition, "clicked",
                    G_CALLBACK (on_btn_exit_std_nutrition_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rech_std_nutrition, "clicked",
                    G_CALLBACK (on_button_rech_std_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Menu_student_nutrition, Menu_student_nutrition, "Menu_student_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, spinbutton_jour_nutrition, "spinbutton_jour_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, spinbutton_mois_nutrition, "spinbutton_mois_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, spinbutton_annnee_nutrition, "spinbutton_annnee_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, treeview1_nutrition, "treeview1_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, image26, "image26");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, btn_exit_std_nutrition, "btn_exit_std_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, image28, "image28");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, label52, "label52");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, label42_nutrition, "label42_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, date_nutrition, "date_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, jour_nutrition, "jour_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, mois_nutrition, "mois_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, button_rech_std_nutrition, "button_rech_std_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, image4, "image4");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, label8, "label8");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, label_annee_nutrition, "label_annee_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_student_nutrition, image27, "image27");

  return Menu_student_nutrition;
}

GtkWidget*
create_Menu_admin_nutrition (void)
{
  GtkWidget *Menu_admin_nutrition;
  GtkWidget *fixed3;
  GtkWidget *fixed9;
  GtkWidget *image18;
  GtkWidget *button_exit_nutrition;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image17;
  GtkWidget *label44;
  GtkWidget *notebook1_nutrition;
  GtkWidget *fixed4;
  GtkWidget *id_nutrition;
  GtkWidget *nom_repas_nutrition;
  GtkObject *jour_nutrition_adj;
  GtkWidget *jour_nutrition;
  GtkObject *mois_nutrition_adj;
  GtkWidget *mois_nutrition;
  GtkObject *annee_nutrition_adj;
  GtkWidget *annee_nutrition;
  GtkWidget *label_add_temps_nutrition;
  GtkWidget *label_add_date_nutrition;
  GtkWidget *label_add_menu_nutrition;
  GtkWidget *label_add_id_nutrition;
  GtkWidget *label14_nutrition;
  GtkWidget *label_id_nutrition;
  GtkWidget *label_jour_nutrition;
  GtkWidget *label_mois_nutrition;
  GtkWidget *label_annee_nutrition;
  GtkWidget *label19_nutrition;
  GtkWidget *image20;
  GtkWidget *label_date_nutrition;
  GtkWidget *combobox1_nutrition;
  GtkWidget *btn_afficher_add_nutrition;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image19;
  GtkWidget *label49;
  GtkWidget *button_add_nutrition;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image24;
  GtkWidget *label50;
  GtkWidget *label_ajouter_nutrition;
  GtkWidget *fixed7;
  GtkWidget *entry2_nutrition;
  GtkWidget *entry3_nutrition;
  GtkObject *spinbutton_jj_nutrition_adj;
  GtkWidget *spinbutton_jj_nutrition;
  GtkObject *spinbutton_mm_nutrition_adj;
  GtkWidget *spinbutton_mm_nutrition;
  GtkObject *spinbutton_aa_nutrition_adj;
  GtkWidget *spinbutton_aa_nutrition;
  GtkObject *spinbutton4_nutrition_adj;
  GtkWidget *spinbutton4_nutrition;
  GtkWidget *label24_nutrition;
  GtkWidget *label25_nutrition;
  GtkWidget *label26_nutrition;
  GtkWidget *label27_nutrition;
  GtkWidget *label28_nutrition;
  GtkWidget *label29_nutrition;
  GtkWidget *label30_nutrition;
  GtkWidget *btn_modify_id_nutrition;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image10;
  GtkWidget *label32;
  GtkWidget *buttn_nom_modify_nutrition;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image9;
  GtkWidget *label31;
  GtkWidget *buttn_date_modify_nutrition;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image11;
  GtkWidget *label33;
  GtkWidget *button_dechets_modify_nutrition;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image12;
  GtkWidget *label34;
  GtkWidget *button_temp_modify_nutrition;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image13;
  GtkWidget *label35;
  GtkWidget *btn_modify_nutrition;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image14;
  GtkWidget *label36;
  GtkWidget *treeview_mf_nutrition;
  GtkWidget *combobox_modif_temps_nutrition;
  GtkWidget *image25;
  GtkWidget *label_mf_nutrition;
  GtkWidget *label10_nutrition;
  GtkWidget *fixed6;
  GtkObject *spinbutton_j_nutrition_adj;
  GtkWidget *spinbutton_j_nutrition;
  GtkObject *spinbutton_m_nutrition_adj;
  GtkWidget *spinbutton_m_nutrition;
  GtkObject *spinbutton_a_nutrition_adj;
  GtkWidget *spinbutton_a_nutrition;
  GtkWidget *label37_nutrition;
  GtkWidget *label39_nutrition;
  GtkWidget *label38_nutrition;
  GtkWidget *label40_nutrition;
  GtkWidget *image21;
  GtkWidget *button_recherche_nutrition;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *label41;
  GtkWidget *image22;
  GtkWidget *label11_nutrition;
  GtkWidget *fixed5;
  GtkWidget *treeview2_nutrition;
  GtkWidget *image23;
  GtkWidget *button_best_menu_nutrition;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image7;
  GtkWidget *label21;
  GtkWidget *button_show_nutrition;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image16;
  GtkWidget *label43;
  GtkWidget *label_afficher_nutrition;

  Menu_admin_nutrition = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Menu_admin_nutrition), _("Menu_admin"));
  gtk_window_set_position (GTK_WINDOW (Menu_admin_nutrition), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (Menu_admin_nutrition), 950, 700);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Menu_admin_nutrition), fixed3);
  gtk_widget_set_size_request (fixed3, 744, 376);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_fixed_put (GTK_FIXED (fixed3), fixed9, 0, 0);
  gtk_widget_set_size_request (fixed9, 900, 500);

  image18 = create_pixmap (Menu_admin_nutrition, "istockphoto-538480782-1024x1024.jpg");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed9), image18, 0, 0);
  gtk_widget_set_size_request (image18, 900, 560);

  button_exit_nutrition = gtk_button_new ();
  gtk_widget_show (button_exit_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed3), button_exit_nutrition, 784, 24);
  gtk_widget_set_size_request (button_exit_nutrition, 64, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_exit_nutrition), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image17 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox14), image17, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Exit"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox14), label44, FALSE, FALSE, 0);

  notebook1_nutrition = gtk_notebook_new ();
  gtk_widget_show (notebook1_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed3), notebook1_nutrition, 0, 48);
  gtk_widget_set_size_request (notebook1_nutrition, 888, 480);
  GTK_WIDGET_UNSET_FLAGS (notebook1_nutrition, GTK_CAN_FOCUS);
  gtk_notebook_set_show_border (GTK_NOTEBOOK (notebook1_nutrition), FALSE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1_nutrition), fixed4);

  id_nutrition = gtk_entry_new ();
  gtk_widget_show (id_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), id_nutrition, 360, 72);
  gtk_widget_set_size_request (id_nutrition, 56, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (id_nutrition), 8226);

  nom_repas_nutrition = gtk_entry_new ();
  gtk_widget_show (nom_repas_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), nom_repas_nutrition, 360, 112);
  gtk_widget_set_size_request (nom_repas_nutrition, 168, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_repas_nutrition), 8226);

  jour_nutrition_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (jour_nutrition_adj), 1, 0);
  gtk_widget_show (jour_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), jour_nutrition, 408, 160);
  gtk_widget_set_size_request (jour_nutrition, 40, 24);

  mois_nutrition_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (mois_nutrition_adj), 1, 0);
  gtk_widget_show (mois_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), mois_nutrition, 408, 192);
  gtk_widget_set_size_request (mois_nutrition, 40, 24);

  annee_nutrition_adj = gtk_adjustment_new (2000, 2000, 2021, 1, 10, 10);
  annee_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (annee_nutrition_adj), 1, 0);
  gtk_widget_show (annee_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), annee_nutrition, 408, 224);
  gtk_widget_set_size_request (annee_nutrition, 80, 24);

  label_add_temps_nutrition = gtk_label_new ("");
  gtk_widget_show (label_add_temps_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label_add_temps_nutrition, 0, 296);
  gtk_widget_set_size_request (label_add_temps_nutrition, 160, 16);

  label_add_date_nutrition = gtk_label_new ("");
  gtk_widget_show (label_add_date_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label_add_date_nutrition, 0, 240);
  gtk_widget_set_size_request (label_add_date_nutrition, 152, 16);

  label_add_menu_nutrition = gtk_label_new ("");
  gtk_widget_show (label_add_menu_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label_add_menu_nutrition, 8, 112);
  gtk_widget_set_size_request (label_add_menu_nutrition, 184, 16);

  label_add_id_nutrition = gtk_label_new ("");
  gtk_widget_show (label_add_id_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label_add_id_nutrition, 0, 72);
  gtk_widget_set_size_request (label_add_id_nutrition, 152, 16);

  label14_nutrition = gtk_label_new (_("Menu :"));
  gtk_widget_show (label14_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label14_nutrition, 272, 120);
  gtk_widget_set_size_request (label14_nutrition, 49, 17);

  label_id_nutrition = gtk_label_new (_("Id :"));
  gtk_widget_show (label_id_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label_id_nutrition, 264, 72);
  gtk_widget_set_size_request (label_id_nutrition, 49, 17);

  label_jour_nutrition = gtk_label_new (_("Jour :"));
  gtk_widget_show (label_jour_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label_jour_nutrition, 328, 168);
  gtk_widget_set_size_request (label_jour_nutrition, 49, 17);

  label_mois_nutrition = gtk_label_new (_("Mois :"));
  gtk_widget_show (label_mois_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label_mois_nutrition, 328, 200);
  gtk_widget_set_size_request (label_mois_nutrition, 49, 17);

  label_annee_nutrition = gtk_label_new (_("Ann\303\251e :"));
  gtk_widget_show (label_annee_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label_annee_nutrition, 328, 232);
  gtk_widget_set_size_request (label_annee_nutrition, 49, 17);

  label19_nutrition = gtk_label_new (_("Le temps du repas:"));
  gtk_widget_show (label19_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label19_nutrition, 264, 280);
  gtk_widget_set_size_request (label19_nutrition, 144, 24);
  gtk_label_set_width_chars (GTK_LABEL (label19_nutrition), 1);

  image20 = create_pixmap (Menu_admin_nutrition, "images1.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed4), image20, 0, 88);
  gtk_widget_set_size_request (image20, 240, 272);

  label_date_nutrition = gtk_label_new (_("Date :"));
  gtk_widget_show (label_date_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), label_date_nutrition, 272, 168);
  gtk_widget_set_size_request (label_date_nutrition, 49, 17);

  combobox1_nutrition = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox1_nutrition, 408, 280);
  gtk_widget_set_size_request (combobox1_nutrition, 80, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_nutrition), _("Petit-d\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_nutrition), _("D\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1_nutrition), _("D\303\256ner"));

  btn_afficher_add_nutrition = gtk_button_new ();
  gtk_widget_show (btn_afficher_add_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), btn_afficher_add_nutrition, 720, 408);
  gtk_widget_set_size_request (btn_afficher_add_nutrition, 120, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (btn_afficher_add_nutrition), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image19 = create_pixmap (Menu_admin_nutrition, "icons8-watermelon-30.png");
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox15), image19, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("<span color=\"darkorange\">Afficher</span>"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox15), label49, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  button_add_nutrition = gtk_button_new ();
  gtk_widget_show (button_add_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed4), button_add_nutrition, 360, 336);
  gtk_widget_set_size_request (button_add_nutrition, 160, 40);
  GTK_WIDGET_SET_FLAGS (button_add_nutrition, GTK_CAN_DEFAULT);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button_add_nutrition), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image24 = create_pixmap (Menu_admin_nutrition, "icons8-cherry-30.png");
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox16), image24, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox16), label50, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  label_ajouter_nutrition = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">Ajouter</span></b>"));
  gtk_widget_show (label_ajouter_nutrition);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1_nutrition), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1_nutrition), 0), label_ajouter_nutrition);
  gtk_label_set_use_markup (GTK_LABEL (label_ajouter_nutrition), TRUE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1_nutrition), fixed7);

  entry2_nutrition = gtk_entry_new ();
  gtk_widget_show (entry2_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), entry2_nutrition, 296, 48);
  gtk_widget_set_size_request (entry2_nutrition, 48, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_nutrition), 8226);

  entry3_nutrition = gtk_entry_new ();
  gtk_widget_show (entry3_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), entry3_nutrition, 144, 96);
  gtk_widget_set_size_request (entry3_nutrition, 200, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_nutrition), 8226);

  spinbutton_jj_nutrition_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jj_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jj_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton_jj_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_jj_nutrition, 88, 160);
  gtk_widget_set_size_request (spinbutton_jj_nutrition, 60, 27);

  spinbutton_mm_nutrition_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_mm_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_mm_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton_mm_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_mm_nutrition, 88, 192);
  gtk_widget_set_size_request (spinbutton_mm_nutrition, 60, 27);

  spinbutton_aa_nutrition_adj = gtk_adjustment_new (1, 2000, 2021, 1, 10, 10);
  spinbutton_aa_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_aa_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton_aa_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton_aa_nutrition, 88, 232);
  gtk_widget_set_size_request (spinbutton_aa_nutrition, 80, 24);

  spinbutton4_nutrition_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton4_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton4_nutrition, 192, 272);
  gtk_widget_set_size_request (spinbutton4_nutrition, 60, 27);

  label24_nutrition = gtk_label_new (_("Veuillez saisir id du menu \303\240 modifier:"));
  gtk_widget_show (label24_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), label24_nutrition, 0, 56);
  gtk_widget_set_size_request (label24_nutrition, 304, 16);

  label25_nutrition = gtk_label_new (_("Nom du menu"));
  gtk_widget_show (label25_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), label25_nutrition, 24, 104);
  gtk_widget_set_size_request (label25_nutrition, 120, 24);

  label26_nutrition = gtk_label_new (_("Jour"));
  gtk_widget_show (label26_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), label26_nutrition, 32, 160);
  gtk_widget_set_size_request (label26_nutrition, 49, 17);

  label27_nutrition = gtk_label_new (_("Mois"));
  gtk_widget_show (label27_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), label27_nutrition, 32, 200);
  gtk_widget_set_size_request (label27_nutrition, 49, 17);

  label28_nutrition = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label28_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), label28_nutrition, 32, 240);
  gtk_widget_set_size_request (label28_nutrition, 49, 17);

  label29_nutrition = gtk_label_new (_("Nombre de d\303\251chets"));
  gtk_widget_show (label29_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), label29_nutrition, 16, 272);
  gtk_widget_set_size_request (label29_nutrition, 176, 32);

  label30_nutrition = gtk_label_new (_("Temps du repas :"));
  gtk_widget_show (label30_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), label30_nutrition, 16, 312);
  gtk_widget_set_size_request (label30_nutrition, 152, 24);

  btn_modify_id_nutrition = gtk_button_new ();
  gtk_widget_show (btn_modify_id_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), btn_modify_id_nutrition, 360, 48);
  gtk_widget_set_size_request (btn_modify_id_nutrition, 40, 24);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (btn_modify_id_nutrition), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image10 = create_pixmap (Menu_admin_nutrition, "icons8-check-32.png");
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox7), image10, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox7), label32, FALSE, FALSE, 0);

  buttn_nom_modify_nutrition = gtk_button_new ();
  gtk_widget_show (buttn_nom_modify_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), buttn_nom_modify_nutrition, 360, 96);
  gtk_widget_set_size_request (buttn_nom_modify_nutrition, 40, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttn_nom_modify_nutrition), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image9 = create_pixmap (Menu_admin_nutrition, "icons8-edit-tool-button-for-composing-draft-page-28.png");
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox6), image9, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox6), label31, FALSE, FALSE, 0);

  buttn_date_modify_nutrition = gtk_button_new ();
  gtk_widget_show (buttn_date_modify_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), buttn_date_modify_nutrition, 200, 192);
  gtk_widget_set_size_request (buttn_date_modify_nutrition, 40, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttn_date_modify_nutrition), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image11 = create_pixmap (Menu_admin_nutrition, "icons8-edit-tool-button-for-composing-draft-page-28.png");
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox8), image11, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox8), label33, FALSE, FALSE, 0);

  button_dechets_modify_nutrition = gtk_button_new ();
  gtk_widget_show (button_dechets_modify_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), button_dechets_modify_nutrition, 336, 272);
  gtk_widget_set_size_request (button_dechets_modify_nutrition, 40, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_dechets_modify_nutrition), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image12 = create_pixmap (Menu_admin_nutrition, "icons8-edit-tool-button-for-composing-draft-page-28.png");
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox9), image12, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox9), label34, FALSE, FALSE, 0);

  button_temp_modify_nutrition = gtk_button_new ();
  gtk_widget_show (button_temp_modify_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), button_temp_modify_nutrition, 336, 304);
  gtk_widget_set_size_request (button_temp_modify_nutrition, 40, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_temp_modify_nutrition), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image13 = create_pixmap (Menu_admin_nutrition, "icons8-edit-tool-button-for-composing-draft-page-28.png");
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox10), image13, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox10), label35, FALSE, FALSE, 0);

  btn_modify_nutrition = gtk_button_new ();
  gtk_widget_show (btn_modify_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), btn_modify_nutrition, 152, 360);
  gtk_widget_set_size_request (btn_modify_nutrition, 336, 56);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (btn_modify_nutrition), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image14 = create_pixmap (Menu_admin_nutrition, "icons8-cute-pumpkin-30.png");
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox11), image14, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Enregistrer les modifications"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox11), label36, FALSE, FALSE, 0);

  treeview_mf_nutrition = gtk_tree_view_new ();
  gtk_widget_show (treeview_mf_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview_mf_nutrition, 424, 80);
  gtk_widget_set_size_request (treeview_mf_nutrition, 464, 72);

  combobox_modif_temps_nutrition = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_modif_temps_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox_modif_temps_nutrition, 192, 312);
  gtk_widget_set_size_request (combobox_modif_temps_nutrition, 80, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modif_temps_nutrition), _("Petit-d\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modif_temps_nutrition), _("D\303\251jeuner"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modif_temps_nutrition), _("D\303\256ner"));

  image25 = create_pixmap (Menu_admin_nutrition, "icons8-citrus-40.png");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed7), image25, 768, 240);
  gtk_widget_set_size_request (image25, 64, 56);

  label_mf_nutrition = gtk_label_new ("");
  gtk_widget_show (label_mf_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed7), label_mf_nutrition, 520, 240);
  gtk_widget_set_size_request (label_mf_nutrition, 232, 48);

  label10_nutrition = gtk_label_new_with_mnemonic (_("<b><span color=\"green\">Modifier</span></b>"));
  gtk_widget_show (label10_nutrition);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1_nutrition), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1_nutrition), 1), label10_nutrition);
  gtk_label_set_use_markup (GTK_LABEL (label10_nutrition), TRUE);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1_nutrition), fixed6);

  spinbutton_j_nutrition_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_j_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_j_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton_j_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_j_nutrition, 328, 48);
  gtk_widget_set_size_request (spinbutton_j_nutrition, 60, 27);

  spinbutton_m_nutrition_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_m_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_m_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton_m_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_m_nutrition, 328, 112);
  gtk_widget_set_size_request (spinbutton_m_nutrition, 60, 27);

  spinbutton_a_nutrition_adj = gtk_adjustment_new (2000, 2000, 2021, 1, 10, 10);
  spinbutton_a_nutrition = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_a_nutrition_adj), 1, 0);
  gtk_widget_show (spinbutton_a_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton_a_nutrition, 328, 168);
  gtk_widget_set_size_request (spinbutton_a_nutrition, 60, 27);

  label37_nutrition = gtk_label_new (_("veuillez saisir la date du menu:"));
  gtk_widget_show (label37_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed6), label37_nutrition, 8, 48);
  gtk_widget_set_size_request (label37_nutrition, 232, 32);

  label39_nutrition = gtk_label_new_with_mnemonic (_("<b>Mois :</b>"));
  gtk_widget_show (label39_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed6), label39_nutrition, 248, 120);
  gtk_widget_set_size_request (label39_nutrition, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label39_nutrition), TRUE);

  label38_nutrition = gtk_label_new_with_mnemonic (_("<b>Jour :</b>"));
  gtk_widget_show (label38_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed6), label38_nutrition, 248, 56);
  gtk_widget_set_size_request (label38_nutrition, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label38_nutrition), TRUE);

  label40_nutrition = gtk_label_new_with_mnemonic (_("<b>Ann\303\251e :</b>"));
  gtk_widget_show (label40_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed6), label40_nutrition, 248, 168);
  gtk_widget_set_size_request (label40_nutrition, 64, 24);
  gtk_label_set_use_markup (GTK_LABEL (label40_nutrition), TRUE);

  image21 = create_pixmap (Menu_admin_nutrition, "images1.jpeg");
  gtk_widget_show (image21);
  gtk_fixed_put (GTK_FIXED (fixed6), image21, 24, 248);
  gtk_widget_set_size_request (image21, 184, 136);

  button_recherche_nutrition = gtk_button_new ();
  gtk_widget_show (button_recherche_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed6), button_recherche_nutrition, 288, 224);
  gtk_widget_set_size_request (button_recherche_nutrition, 184, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_recherche_nutrition), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  label41 = gtk_label_new_with_mnemonic (_("<b><span color=\"salmon\">Rechercher</span></b>"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox12), label41, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  image22 = create_pixmap (Menu_admin_nutrition, "kawaii-french-fries.png");
  gtk_widget_show (image22);
  gtk_fixed_put (GTK_FIXED (fixed6), image22, 496, 184);
  gtk_widget_set_size_request (image22, 80, 80);

  label11_nutrition = gtk_label_new_with_mnemonic (_("<b><span color=\"purple\">Rechercher</span></b>"));
  gtk_widget_show (label11_nutrition);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1_nutrition), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1_nutrition), 2), label11_nutrition);
  gtk_label_set_use_markup (GTK_LABEL (label11_nutrition), TRUE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1_nutrition), fixed5);
  gtk_container_set_border_width (GTK_CONTAINER (fixed5), 6);

  treeview2_nutrition = gtk_tree_view_new ();
  gtk_widget_show (treeview2_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview2_nutrition, 0, 30);
  gtk_widget_set_size_request (treeview2_nutrition, 568, 290);

  image23 = create_pixmap (Menu_admin_nutrition, "images5.png");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed5), image23, 640, 152);
  gtk_widget_set_size_request (image23, 132, 130);

  button_best_menu_nutrition = gtk_button_new ();
  gtk_widget_show (button_best_menu_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed5), button_best_menu_nutrition, 536, 320);
  gtk_widget_set_size_request (button_best_menu_nutrition, 296, 50);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_best_menu_nutrition), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image7 = create_pixmap (Menu_admin_nutrition, "icons8-kawaii-pizza-40.png");
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox4), image7, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Afficher meilleur menu de la semaine"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox4), label21, FALSE, FALSE, 0);

  button_show_nutrition = gtk_button_new ();
  gtk_widget_show (button_show_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed5), button_show_nutrition, 560, 88);
  gtk_widget_set_size_request (button_show_nutrition, 296, 50);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_show_nutrition), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image16 = create_pixmap (Menu_admin_nutrition, "icons8-kawaii-cupcake-40.png");
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox13), image16, FALSE, FALSE, 0);
  gtk_widget_set_size_request (image16, 50, 50);

  label43 = gtk_label_new_with_mnemonic (_("     Afficher tous"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox13), label43, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label43, 102, 5);

  label_afficher_nutrition = gtk_label_new_with_mnemonic (_("<b><span color=\"grey\">Afficher</span></b>"));
  gtk_widget_show (label_afficher_nutrition);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1_nutrition), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1_nutrition), 3), label_afficher_nutrition);
  gtk_label_set_use_markup (GTK_LABEL (label_afficher_nutrition), TRUE);

  g_signal_connect ((gpointer) button_exit_nutrition, "clicked",
                    G_CALLBACK (on_button_exit_nutrition_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_afficher_add_nutrition, "clicked",
                    G_CALLBACK (on_btn_afficher_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_add_nutrition, "clicked",
                    G_CALLBACK (on_button_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_modify_id_nutrition, "clicked",
                    G_CALLBACK (on_btn_modify_id_nutrition_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttn_nom_modify_nutrition, "clicked",
                    G_CALLBACK (on_buttn_nom_modify_nutrition_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttn_date_modify_nutrition, "clicked",
                    G_CALLBACK (on_buttn_date_modify_nutrition_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_dechets_modify_nutrition, "clicked",
                    G_CALLBACK (on_button_dechets_modify_nutrition_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_temp_modify_nutrition, "clicked",
                    G_CALLBACK (on_button_temp_modify_nutrition_clicked),
                    NULL);
  g_signal_connect ((gpointer) btn_modify_nutrition, "clicked",
                    G_CALLBACK (on_btn_modify_nutrition_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_mf_nutrition, "row_activated",
                    G_CALLBACK (on_treeview_mf_nutrition_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_recherche_nutrition, "clicked",
                    G_CALLBACK (on_button_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2_nutrition, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_best_menu_nutrition, "clicked",
                    G_CALLBACK (on_button_best_menu_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_show_nutrition, "clicked",
                    G_CALLBACK (on_button_show_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label_ajouter_nutrition), button_exit_nutrition);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label10_nutrition), button_exit_nutrition);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label40_nutrition), spinbutton_a_nutrition);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label11_nutrition), button_exit_nutrition);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label_afficher_nutrition), button_exit_nutrition);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Menu_admin_nutrition, Menu_admin_nutrition, "Menu_admin_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image18, "image18");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, button_exit_nutrition, "button_exit_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image17, "image17");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label44, "label44");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, notebook1_nutrition, "notebook1_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, id_nutrition, "id_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, nom_repas_nutrition, "nom_repas_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, jour_nutrition, "jour_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, mois_nutrition, "mois_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, annee_nutrition, "annee_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_add_temps_nutrition, "label_add_temps_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_add_date_nutrition, "label_add_date_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_add_menu_nutrition, "label_add_menu_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_add_id_nutrition, "label_add_id_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label14_nutrition, "label14_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_id_nutrition, "label_id_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_jour_nutrition, "label_jour_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_mois_nutrition, "label_mois_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_annee_nutrition, "label_annee_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label19_nutrition, "label19_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image20, "image20");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_date_nutrition, "label_date_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, combobox1_nutrition, "combobox1_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, btn_afficher_add_nutrition, "btn_afficher_add_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image19, "image19");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label49, "label49");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, button_add_nutrition, "button_add_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image24, "image24");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label50, "label50");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_ajouter_nutrition, "label_ajouter_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, entry2_nutrition, "entry2_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, entry3_nutrition, "entry3_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, spinbutton_jj_nutrition, "spinbutton_jj_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, spinbutton_mm_nutrition, "spinbutton_mm_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, spinbutton_aa_nutrition, "spinbutton_aa_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, spinbutton4_nutrition, "spinbutton4_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label24_nutrition, "label24_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label25_nutrition, "label25_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label26_nutrition, "label26_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label27_nutrition, "label27_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label28_nutrition, "label28_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label29_nutrition, "label29_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label30_nutrition, "label30_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, btn_modify_id_nutrition, "btn_modify_id_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image10, "image10");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label32, "label32");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, buttn_nom_modify_nutrition, "buttn_nom_modify_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image9, "image9");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label31, "label31");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, buttn_date_modify_nutrition, "buttn_date_modify_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image11, "image11");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label33, "label33");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, button_dechets_modify_nutrition, "button_dechets_modify_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image12, "image12");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label34, "label34");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, button_temp_modify_nutrition, "button_temp_modify_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image13, "image13");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label35, "label35");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, btn_modify_nutrition, "btn_modify_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image14, "image14");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label36, "label36");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, treeview_mf_nutrition, "treeview_mf_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, combobox_modif_temps_nutrition, "combobox_modif_temps_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image25, "image25");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_mf_nutrition, "label_mf_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label10_nutrition, "label10_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, spinbutton_j_nutrition, "spinbutton_j_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, spinbutton_m_nutrition, "spinbutton_m_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, spinbutton_a_nutrition, "spinbutton_a_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label37_nutrition, "label37_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label39_nutrition, "label39_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label38_nutrition, "label38_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label40_nutrition, "label40_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image21, "image21");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, button_recherche_nutrition, "button_recherche_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label41, "label41");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image22, "image22");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label11_nutrition, "label11_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, treeview2_nutrition, "treeview2_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image23, "image23");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, button_best_menu_nutrition, "button_best_menu_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image7, "image7");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label21, "label21");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, button_show_nutrition, "button_show_nutrition");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, image16, "image16");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label43, "label43");
  GLADE_HOOKUP_OBJECT (Menu_admin_nutrition, label_afficher_nutrition, "label_afficher_nutrition");

  gtk_widget_grab_default (button_add_nutrition);
  return Menu_admin_nutrition;
}

GtkWidget*
create_window1_nutrition (void)
{
  GtkWidget *window1_nutrition;
  GtkWidget *fixed8;
  GtkWidget *label44_nutrition;

  window1_nutrition = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1_nutrition), _("window1"));
  gtk_window_set_default_size (GTK_WINDOW (window1_nutrition), 300, 300);
  gtk_window_set_icon_name (GTK_WINDOW (window1_nutrition), "gtk-dialog-error");

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (window1_nutrition), fixed8);

  label44_nutrition = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">Veuillez vous inscrire pour acc\303\251der \303\240 la platform</span></b>"));
  gtk_widget_show (label44_nutrition);
  gtk_fixed_put (GTK_FIXED (fixed8), label44_nutrition, 80, 104);
  gtk_widget_set_size_request (label44_nutrition, 424, 80);
  gtk_label_set_use_markup (GTK_LABEL (label44_nutrition), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1_nutrition, window1_nutrition, "window1_nutrition");
  GLADE_HOOKUP_OBJECT (window1_nutrition, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (window1_nutrition, label44_nutrition, "label44_nutrition");

  return window1_nutrition;
}

